#cloud-config
timezone: Europe/Istanbul
users:
  - name: slcn8n
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHG+rsBXA45AenfPEfXynmlY94cwRZGclqsr7uEDx07kCFOZWqcgPHfQN1WL0v0gxAngpEvwdsxZtYItQXm0Cohui8OGcJafC6P1JE5PGqrE6eOHl2zfySjYBIaXB6aLEZDX8BNmLD2howAclgnl0UQ6CYXd26BPJjWgwfbDmvhr9NIFqMeC5nuQgXkTxi29aoNiwWCN9tyLjbn/1M+CtVUxJ1sstpb0ZgJ6/LY6+HlLqRNoPpxMCEldS9rw6u193rp6RYiMIWqfE0LT6MCgl0glMA6IzZsejZryyuZgJKTHN/DbKGI0YYQhM+xDuXS/yvdC9Gkjujq6/FtG/ceRxNQU9mEtHFNsW3RuDL4dqbtJZJvQDpLABcsiK2PT37m9za19qqwH3eD5JkDHhsjvvea1izhWo8+/ZVbPHz7mhLFdo1LO0u6TV3f3CjkDQuk/7YGpGJ1DYtctnxcaGo/OHCccptG55MgEYgL9Gw6fR1PcP2QuUIBHOE7hFFZADl+4lygF9tONaQhpCl4RqdVv0QbM8aCEbg6FwDDoiZpWtA9R3/lzRsvBJBQhO1MHwt4eZV4YTo3KhvctOLBNJHlrFkBdTl/1Kkh/a85nQYY5UKlfphNIwjy6OSjIZt53pS/3brdTML8D8ujroyCyAVEgxm2enAMZRivkDs2fIb9nB5KQ== selcu@selcuk-pc
packages:
  - fail2ban
  - ufw
package_update: true
package_upgrade: true
runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow OpenSSH
  - ufw enable
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)KbdInteractiveAuthentication/s/^.*$/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)ChallengeResponseAuthentication/s/^.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers slcspa' /etc/ssh/sshd_config
  - reboot
