services:
  # NODE.JS APPLICATION
  s_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: c_node_slcapp
    restart: unless-stopped
    environment:
      NODE_ENV: production
      TZ: ${TZ}
      PORT: ${PORT}
      ORIGIN: ${ORIGIN}
      BODY_SIZE_LIMIT: ${BODY_SIZE_LIMIT}
      PB_PORT: ${PB_PORT}
      PB_BACKEND_URL: ${PB_BACKEND_URL}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      s_pocketbase:
        condition: service_healthy
    networks:
      - network_0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:${PORT}/robots.txt"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s

  # POCKETBASE SQLITE DB
  s_pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pb
    container_name: c_pocketbase_slcapp
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
    ports:
      - ${PB_PORT}:${PB_PORT}
    networks:
      - network_0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:${PB_PORT}/api/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  network_0:
    driver: bridge
